apiVersion: apps/v1
kind: Deployment
metadata:
  name: wft-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wft
  template:
    metadata:
      labels:
        app: wft
    spec:
      containers:
        - name: wft
          image: mubasherm/weatherfetcher:v2
