apiVersion: apps/v1
kind: Deployment
metadata:
    name: atnt-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: atnt
    template:
        metadata:
            labels: {app: atnt}
        spec:
            containers: [{name: atnt, image: 'mubasherm/allthenews:v3', args: [news, 'http://nf-service:8888', weather, 'http://wf-service:8888'], ports: [{containerPort: 8080}]}, {name: atn-redis, image: redis, ports: [{containerPort: 31826}]}]
