apiVersion: v1
kind: Service
metadata:
  name: atnt-service
  labels:
    app: atnt-service
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 8080
    nodePort: 31826
  selector:
    app: atnt
  type: NodePort
