apiVersion: v1
kind: Service
metadata:
  name: wft-service
  labels:
    name: wft-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: wft
  type: ClusterIP
